### ISSUE TITLE
Doesn't fill full area of large width of element.

### ISSUE THREAD

**Issue by ashishkumawat** [qqnc/nc-ripple#1]
Ripple effect disappear without filling full width of large width button.

**Comment by nch3ng** [comment]
You can use r-size to determine the ripple size, maybe you can set the size over your button, and set longer duration to expand slower.  You can check the options.  I'll close if it's not an issue.   Ex:

```
<a href='' style="width:600px;" class='btn btn-md btn-large btn-block' r-duration='5.5' r-size='1200' nc-ripple style=''>Button</a> 
```
